name: metrics
on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  # (optional) Run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: weightedangelcube
          template: classic
          base: ""
          config_timezone: America/Edmonton
          
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: programming
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_achievements_limit: 2
          plugin_steam_playtime_threshold: 2
          plugin_steam_recent_games_limit: 3
          plugin_steam_sections: recently-played
          plugin_steam_user: 76561199245582776

          plugin_music: yes
          plugin_music_token: ${{ secrets.LASTFM_TOKEN }}
          plugin_music_provider: lastfm
          plugin_music_user: angelcube__
          plugin_music_limit: 4
          plugin_music_mode: recent
