name: metrics-languages
on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  # (optional) Run workflow manually
  workflow_dispatch:
  push: { branches: ["main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          filename: generated/metrics-languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""

          plugin_languages: yes
          # plugin_languages_indepth: broken
          plugin_languages_ignored: html, css, scss
          plugin_languages_skipped: weightedangelcube/web
          plugin_languages_sections: most-used
          plugin_languages_categories: programming
          plugin_languages_details: percentage, lines
          plugin_languages_limit: 8
          plugin_languages_other: true
          commits_authoring: angel@angelcube.dev, 144711471+weightedangelcube@users.noreply.github.com
